### ISSUE TITLE
感谢作者的辛勤付出，打赏弹窗能否指定在当前视野中弹出，谢谢

### ISSUE THREAD

**Issue by LyleLee** [sinchang/vdonate#1]
提个小意见，点击打赏按钮之后，出现的打赏二维码能否出现在当前视野的中央。

**Comment by sinchang** [comment]
这样的话，切换按钮和提示文字就不好处理了……

**Comment by LyleLee** [comment]
我打算这样处理：

id="donate-modal-container"
把整个弹窗的CSS属性中top 设置成网页的中间位置

**Comment by LyleLee** [comment]
我打算这样处理：

id="donate-modal-container"
把整个弹窗的CSS属性中top 设置成网页的中间位置

**Comment by sinchang** [comment]
可以的话贴下你想法的 css 代码实现。

**Comment by LyleLee** [comment]
'
jQuery.fn.center = function () {
    this.css("position","absolute");
    this.css("top", ( $(window).height() - this.height() ) / 2+$(window).scrollTop() + "px");
    this.css("left", ( $(window).width() - this.width() ) / 2+$(window).scrollLeft() + "px");
    return this;
}
$("#donate").click(function(){
	$("#donate-modal-container").center();
});
'
