### ISSUE TITLE
如何设置默认选中的支付方式？

### ISSUE THREAD

**Issue by maoruibin** [sinchang/vdonate#2]
首先感谢作者的作品。

我想默认选中支付宝 并把支付宝放在左边，如何设置？我看了代码，试着修改了下，没有起作用。

谢谢。

**Comment by sinchang** [comment]
你可以手动触发点击事件到「支付宝」按钮。源码顺序是写死的，后续改进下。

**Comment by maoruibin** [comment]
嗯嗯 刚又直接去改了 min.js 可以了，thanks ~
