### ISSUE TITLE
您好，按照readme方法试过了，但是点击打赏没有反应

### ISSUE THREAD

**Issue by songapore** [sinchang/vdonate#4]

**Comment by sinchang** [comment]
请把重现的代码到 codepen 或者 jsbin

**Comment by songapore** [comment]
嗯嗯，感谢回复，我会去尝试。
[把 css文件和 js文件放在 Github 里，可以在写网页的时候直接调用吗？](https://www.zhihu.com/question/22004590/answer/149633324)
会不会是js的路径的问题呢

**Comment by verazuo** [comment]
发现了一个有点尴尬的问题，赞赏功能配置好后，如果那个文章比较长，那么赞赏的幕布会移到屏幕最顶端，而不是浮动在窗口上
如图所示
![image](https://user-images.githubusercontent.com/16172194/39672851-ba06584c-5164-11e8-836a-77e6fe866a5e.png)
